data:
  tokenizer: null
  val_files: ~/data/rlhf/gsm8k/test.parquet
  prompt_key: prompt
  max_prompt_length: 512
  max_response_length: 512
  max_start_length: 256
  max_tool_response_length: 512
  return_raw_chat: False
  shuffle: True
  filter_overlong_prompts: False
  truncation: error
  image_key: images
  use_custom_tool_format_func: False

actor_rollout_ref:
  model:
    path: ~/models/deepseek-llm-7b-chat
    external_lib: null
    override_config: { }
  rollout:
    val_kwargs:
      top_k: -1
      top_p: 1.0
      temperature: 0
      n: 1
      do_sample: False

custom_reward_function:
  path: null
  name: compute_score

trainer:
  project_name: verl_examples
  experiment_name: gsm8k
  logger: [ 'console', 'wandb' ]
  val_generations_to_log_to_wandb: 0
  nnodes: 1
  n_gpus_per_node: 1
  default_local_dir: checkpoints/${trainer.project_name}/${trainer.experiment_name}

tool:
  max_turns: 10
  maxstep: 10
  topk: 5
  shuffle: True
  force_noloop: False
  use_batch_tool_calls: True
  tool_call_start: <tool_call>
  tool_call_end: </tool_call>
  tool_response_start: <tool_response>
  tool_response_end: </tool_response>
  tool_custom_response_template: |

    <|im_start|>user
    <tool_response>
    {tool_response}
    </tool_response><|im_end|>
    <|im_start|>assistant
    <think>
  env: search
  use_api_model: False
  api_model_name: ""
